### ISSUE TITLE
Missing icon for Check File Fingerprint

### ISSUE THREAD

**Issue by mrchief** [jenkins-contrib-themes/jenkins-material-theme#14]
Looks like the corresponding SVG is missing:

![image](https://cloud.githubusercontent.com/assets/781818/12590407/e6309162-c430-11e5-931c-e8d2fae79406.png)

**Comment by afonsof** [comment]
Are you using a plugin that shows that option? I can't see it in my Jenkins.

**Comment by rbywater** [comment]
I'm also having problems with a couple of other icons missing currently on the Node list screen. Namely the Computer "offline" icon (the one that is usually the computer with a red cross, and also the New Node  menu option.

**Comment by mrchief** [comment]
Its a native Jenkins feature as far as google tells me with no option to disable it. 

@rbywater I haven't created any fingerprints. Its a brand new server with a handful jobs and I was in fact looking to disable it when I learnt that it can't be done.

**Comment by afonsof** [comment]
@mrchief what's your Jenkins version? I'll try to simulate your problem.

@rbywater I found a problem in Node Management screen:
![image](https://cloud.githubusercontent.com/assets/805511/12615975/f10832e2-c4ef-11e5-8fb0-238ee62917b7.png).
BTW, Could you send me the html of the offline node icon (including the css classes)?

**Comment by mrchief** [comment]
I'm on 1.613.

**Comment by mrchief** [comment]
Environment variables icon is missing as well (this is a plugin by the way):

![image](https://cloud.githubusercontent.com/assets/781818/12617230/b8474852-c4dc-11e5-8aa2-aa6912bee562.png)

![image](https://cloud.githubusercontent.com/assets/781818/12617234/bc1b81a0-c4dc-11e5-9238-51ed3cb52386.png)

**Comment by rbywater** [comment]
@afonsof Is this what you are after?

```<img style="width: 32px; height: 32px; " alt="[offline]" class="icon-computer-x icon-lg" src="/ci/static/83b50bfc/images/32x32/computer-x.png">```

Let me know if you need more.

**Comment by afonsof** [comment]
Yup this is what I need. Thanks :+1:

**Comment by afonsof** [comment]
@rbywater take a look:
![image](https://cloud.githubusercontent.com/assets/805511/12687131/13abf0ba-c6b5-11e5-8706-8bf713770629.png)

**Comment by rbywater** [comment]
Looks good to me. Just realised there's also the Build Executor Status version (the one on the home page that lists all the nodes) which has HTML of 
```<img style="width: 16px; height: 16px; " class="icon-computer-x icon-sm" src="/ci/static/83b50bfc/images/16x16/computer-x.png">```

Not sure if that's covered by the existing change or not.

**Comment by afonsof** [comment]
@rbywater I hope so. I'm matching the style by the class `icon-computer-x`

**Comment by nfalco79** [comment]
me too missing the check fingerprint SVG

**Comment by mrchief** [comment]
@afonsof Are the fingerprint and env variables icons available now?

**Comment by afonsof** [comment]
@mrchief it's fixed in version 1.1.10. Pay attention to the new css url: http://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-light.css

**Comment by afonsof** [comment]
@mrchief please test and report me if it's ok because I can't see the fingerprint menu in my jenkins.

**Comment by mrchief** [comment]
Will check and let you know. Thanks!
