### ISSUE TITLE
Line in build history over icon

### ISSUE THREAD

**Issue by jhasse** [jenkins-contrib-themes/jenkins-material-theme#21]
![buildhistory](https://cloud.githubusercontent.com/assets/80071/12675733/a11449d0-c68c-11e5-99a1-7180db4bb216.png)

Windows 10, tested with Firefox and Edge.

**Comment by afonsof** [comment]
I cannot reproduce in my Mac OS Firefox. Take a look:
![image](https://cloud.githubusercontent.com/assets/805511/12736136/d6512b36-c934-11e5-9975-00c97a41b1a9.png)

**Comment by jhasse** [comment]
You'll need to queue a build or have one in progress to make the line appear :)

**Comment by nfalco79** [comment]
To reproduce the issue open in Firefox browser or add a long description to a build so build data goes on second line.

**Comment by dep** [comment]
I can reproduce this in Chrome, OSX:

!http://dl.dpeck.net/1703U+

**Comment by afonsof** [comment]
@dep you're using **jenkins-neo-theme** or **jenkins-material-theme**? Your screenshot looks like you are using **neo**. I've just tried to reproduce in MacOS Chrome using **material** but I got the result:
![image](https://cloud.githubusercontent.com/assets/805511/13091432/5b364bde-d4e2-11e5-8774-2523ff3ea06f.png)

**Comment by jhasse** [comment]
@afonsof: as nfalco79 said: you need to "add a long description to a build so build data goes on second line."

**Comment by afonsof** [comment]
@jhasse yes, this is reproducible. What I mentioned was the bug "4-digit build numbers".

**Comment by jhasse** [comment]
Ah okay. It looks like in dep's screenshot that the build number 1300 is working, have you tried # 1301 or # 1296?

**Comment by cobexer** [comment]
I have the same problem with build names like: ```99.9.999```, maybe the fix here could also take care of them :)

**Comment by afonsof** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/805511/13549238/38dbd156-e2e0-11e5-9514-f8ebd0ea7bc2.png)
