### ISSUE TITLE
In progress icon not seen

### ISSUE THREAD

**Issue by znorris** [jenkins-contrib-themes/jenkins-material-theme#36]
When looking at a view of a Project that's in progress I see no icon. I do see the tooltip.

Element: `<img src="/static/0027ac25/images/32x32/aborted_anime.gif" alt="In progress" tooltip="In progress" style="width: 32px; height: 32px; " class="icon-aborted-anime icon-lg" title="In progress">`

**Comment by afonsof** [comment]
@znorris thanks a lot for filing this issue! Could you send me a screenshot?

**Comment by jhasse** [comment]
![in-progress](https://cloud.githubusercontent.com/assets/80071/12921961/d8939eda-cf4f-11e5-96dd-28d2dda2484f.png)
Second bubble is blank, should be the spinning arrows.

**Comment by afonsof** [comment]
Done in core theme
