### ISSUE TITLE
When we open Console page the Executed Target has dot before name

### ISSUE THREAD

**Issue by nfalco79** [jenkins-contrib-themes/jenkins-material-theme#39]
When we open Console page the Executed Target has dot before name.
![dotted_steps](https://cloud.githubusercontent.com/assets/4160180/12979767/79f2c30c-d0d9-11e5-910a-00e9c36e2cbc.jpg)
Original jenkins page align the "Executed Targets" table to the border left so 

> list style is hidden.

![origina](https://cloud.githubusercontent.com/assets/4160180/12549182/b90d19ec-c35b-11e5-8ef3-ae51bc9f7113.jpg)

Already fix on rackspace repository https://github.com/rackerlabs/canon-jenkins/issues/21

**Comment by afonsof** [comment]
@nfalco79: Fixed in version 1.1.10
