### ISSUE TITLE
dist url is broken

### ISSUE THREAD

**Issue by maorhayoun** [jenkins-contrib-themes/jenkins-material-theme#40]
http://afonsof.github.io/jenkins-material-theme/dist/material-light.css  returns 404

**Comment by afonsof** [comment]
I'm sorry, we're moving it to another repo http://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-light.css returns 404

**Comment by afonsof** [comment]
Fixed, it's working but this url is deprecated. For further installations please use the url: http://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-light.css

**Comment by maorhayoun** [comment]
thanks! :+1:
