### ISSUE TITLE
Global build history icon issues

### ISSUE THREAD

**Issue by cyotek** [jenkins-contrib-themes/jenkins-material-theme#41]
Hello,

If you use "Large" icons, then the global build history view (the one accessed via `/view/All/builds`, not the sidebar version displayed for individual projects) looks fine

![global-build-large](https://cloud.githubusercontent.com/assets/859574/12982602/585776c6-d0dd-11e5-8136-eb7765ab5cfa.png)

When set to "Medium", the new icons appear tiled behind the old

![global-build-medium](https://cloud.githubusercontent.com/assets/859574/12982603/58582012-d0dd-11e5-9d93-a4ccf5e0d023.png)

And in "Small" (the setting I tend to use), you can just see the new icon behind the old, in addition the console icon is the default.

![global-build-small](https://cloud.githubusercontent.com/assets/859574/12982601/5855aeb8-d0dd-11e5-97cd-44a0f4d78703.png)

I don't use this view very often, so minor issue as far as I'm concerned but thought I'd better mention it :)

(Screenshots taken from 1.1.9 from the new dist URL)

**Comment by afonsof** [comment]
Thanks a lot for filing this issue! I'll take a look at it as soon as possible!

**Comment by cyotek** [comment]
I've used that view exactly once so no need to hurry on my part :) But fantastic work on the theme as a whole - I really did not like the default look and it's amazing how much a touch of paint helps!
