### ISSUE TITLE
Logo change

### ISSUE THREAD

**Issue by deimosfr** [jenkins-contrib-themes/jenkins-material-theme#45]
Hi,

It would be nice to easily be able to change the logo. My 2 cents...

Thx

**Comment by aarjithn** [comment]
It is pretty easy to do in less. Just add below to #header in style.less

```
background: url('your logo path.png') no-repeat, @color-primary;
background-size: auto 64px, cover; 
```

also need to hide the default image, as jenkins use img tags than background-image. But make sure href that wraps around still works.
```
#jenkins-home-link img {
   opacity: 0;
}
```

**Comment by afonsof** [comment]
I'll thinking about creating a javascript script builder where you select the image and it's inserted inside the css file. All in front end. Anyone would like to help me?

**Comment by aarjithn** [comment]
How would we persist the image, if done in javascript? 
You can't modify the actual css file from front-end, and any injected style would be lost on refresh.

**Comment by deimosfr** [comment]
Thanks for the answre @aarjithn. However I've no logo anymore due to opacity and do not have my wished logo. Any idea ?

**Comment by aarjithn** [comment]
Could you check if the path to logo is correct, and it background is not overwritten by any other styles? I do use this setup for my organisation with custom logo and it works fine.

**Comment by afonsof** [comment]
This is my idea: http://jsfiddle.net/afonsof/s4uuza6u/3/
In that case I'd like to offer the theme only for download. The github hosted installation option would not be available.

**Comment by afonsof** [comment]
@deimosfr I created a tool in the website that allows to set your own logo: http://jenkins-contrib-themes.github.io/jenkins-material-theme/
