### ISSUE TITLE
animated versions of clock and nobuilt icons are missing

### ISSUE THREAD

**Issue by marc-guenther** [jenkins-contrib-themes/jenkins-material-theme#49]
The following two icons appear blank:
- the animated `nobuilt` icon for a new job that is currently building (which looks identical to the grey blinking icon)
- the animated `clock` icon for the Build Now icon for a job that is scheduled to build, but is waiting in the queue for the next executor

To reproduce:
- generate a new job which does 'sleep 300'
- go to a list view which shows Build Button and Status for that job
- take Jenkins offline
- click the build button and reload page
- The button has vanished, but should show the animated build button
- take Jenkins online again
- Build button has reappeared, but now the status icon has vanished.

**Comment by marc-guenther** [comment]
Progress bar in Build Executor Status on the left is also missing for newly created running jobs...

**Comment by afonsof** [comment]
Thanks a lot for filing this issue! We'll take a look at it as soon as possible! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by marc-guenther** [comment]
Sure.

If I understand this correctly, the actual problem is in the core theme, not this one? Unfortunately I could not figure out how to build it, it is missing a grunt file for example, and npm install doesn't do anything

**Comment by afonsof** [comment]
Fixed in https://github.com/jenkins-contrib-themes/jenkins-core-theme/issues/2 and https://github.com/jenkins-contrib-themes/jenkins-core-theme/issues/3
