### ISSUE TITLE
Credentials icon scaled to double size

### ISSUE THREAD

**Issue by cyotek** [jenkins-contrib-themes/jenkins-material-theme#51]
Hello,

Recently I updated the core plugins for my Jenkins installation, and every since the Credentials icon displayed in the sidebar is double the size it should be:

![menu](https://cloud.githubusercontent.com/assets/859574/13372002/2776113c-dd2d-11e5-8927-9241c4389173.png)

Not really sure if this is something you can fix or not, as the relevant HTML has conflicting attributes

    <a href="/credential-store" class="task-icon-link">
      <img src="/static/12efab6f/plugin/credentials/images/48x48/credentials.png" 
      style="width: 48px; height: 48px; width: 24px; height: 24px; margin: 2px;" 
      class="icon-credentials-credentials icon-xlg"
    </a>

Oddly enough if the material theme is disabled, the original credentials icon appears appears at the correct 24x24 size.

I've reported this as a bug with the credentials plugin, but thought I'd also report it here too as there is a different in sizes between native and with the material theme.

**Comment by go2sh** [comment]
I also can confirm the bug. It seems, that its related to the ` icon-xlg ` class. If you change it to ` icon-md` every thing is fine.

**Comment by nfalco79** [comment]
This issue should be moved to core-theme project.
I have no issue using this them (ensure you are using the correct url in instead neo-theme).
This is the sidebar
![desktop](https://cloud.githubusercontent.com/assets/4160180/13526655/961b8dde-e209-11e5-8f60-6c53639306de.jpg)
This is the jenkins->menu
![menu](https://cloud.githubusercontent.com/assets/4160180/13526661/9c2d99f6-e209-11e5-8296-936db529b29c.jpg)

**Comment by cyotek** [comment]
I am using the correct URL - http://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-light.css, although as I noted, that doesn't seem to be a bug with the theme (as it can't influence the wrong class names and size attributes). I reported it here as well simply because there was a discrepancy in sizes when using themed versus unthemed and I was curious as to if there was something the theme could override to correct.

As for "core-theme", I wasn't aware this theme was linked to something else, I assumed it was stand alone.

However, I just tested the Neo theme too and observed the same behaviour as with this theme, i.e. a big credentials icon.

**Comment by afonsof** [comment]
@cyotek the icon is right sized for me too. That's weird. This is my icon html:
```<img style="width: 24px; height: 24px; margin: 2px;" alt="" src="/static/f72481f6/plugin/credentials/images/48x48/credentials.png">```

Could you check what's your credentials version? Mine is 1.2.4.

**Comment by cyotek** [comment]
It's 1.2.5, this issue happened after upgrading from 1.2.4 - perhaps I should have been slightly more specific in my initial description rather than "just upgrading core plugins".

When I first found this issue, I reverted back to 1.2.4 and confirmed the issue wasn't present, but as soon as upgraded back to the latest version the issue was back. I've left the latest version installed as... well, it's the latest version :)

**Comment by afonsof** [comment]
Anyway I hope I've fixed any kind of anomaly.

**Comment by cyotek** [comment]
Seems to be working great with v1.2 of the theme, thanks :)
