### ISSUE TITLE
Progressbar inside job view isn't updated

### ISSUE THREAD

**Issue by derdanne** [jenkins-contrib-themes/jenkins-material-theme#52]
The progressbar inside a job view is not updated during a job run, so it seems the job is running endless.

At the global view of the build processor status on the Jenkins main page the progressbar works flawless.

**Comment by afonsof** [comment]
Hi @derdanne. Thanks for filling this issue. Could you reproduce this problem disabling jenkins material theme?

**Comment by derdanne** [comment]
Ah, sorry - seems that this is a bug in Jenkins LTS.
