### ISSUE TITLE
Specify "https" protocol in README in installation section

### ISSUE THREAD

**Issue by julenpardo** [jenkins-contrib-themes/jenkins-material-theme#53]
First of all, thank for this awesome theme, makes Jenkins look so great.

This is only a little suggestion. It would be nice to specify, in Installation section, `https` protocol in the URL, because, if the site is `https`, the browser will filter the content since is mixed "active" content. And perhaps someone doesn't realise this and can get desperated trying to get the theme load (actually happened to me, but it's not the first time that I've been fighting with mixed contents and I realised quite soon)!

Thanks again for the nice theme!

**Comment by infabo** [comment]
This does not work, because https://afonsof.com/jenkins-material-theme/dist/material-<color>.css does not provide a SSL certificate and so any browser will silently disallows download.
