### ISSUE TITLE
Missing icon for a project with GitLab Logo plugin

### ISSUE THREAD

**Issue by Alexhha** [jenkins-contrib-themes/jenkins-material-theme#56]
Hello,

it seems that [Gitlab Logo plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Logo+Plugin) doesn't work correctly with material design theme.

Default theme - http://i.imgur.com/U8McAu2.png
Material design theme - http://i.imgur.com/pecUE8t.png

**Comment by afonsof** [comment]
@jamroks I've just updated the theme to the version 1.2.2. No icon will be blank anymore. Unfortunately this change has increased the file size a little bit.
