### ISSUE TITLE
Missing manage jenkins icon [Jenkins 2.0]

### ISSUE THREAD

**Issue by jamroks** [jenkins-contrib-themes/jenkins-material-theme#57]
Hi,

 Thanks for the beautiful theme. i just made a fresh install of jenkins then install the theme following the recommended way in the doc (Using the github page Url ). everything went smoothly, but as you can see in the image below there is a messing icon in the menu en the left for the "manage jenkins" section. Do you have any idea of how or what i might check on my side to fix this ? 
My setup is : 

- MacOSX El Capitan
- Safari Version 9.0.3 (11601.4.4)
- Jenkins 2.0-beta-1

<img width="718" alt="screen shot 2016-03-24 at 13 33 26" src="https://cloud.githubusercontent.com/assets/357258/14017089/18822880-f1c5-11e5-9054-92e9daa2e44b.png">

<img width="804" alt="screen shot 2016-03-24 at 13 24 20" src="https://cloud.githubusercontent.com/assets/357258/14017065/d0e6dc28-f1c4-11e5-89c4-86e26bfa7e64.png">

**Comment by afonsof** [comment]
@jamroks thanks for filling this issue. Unfortunately jenkins-material-theme does not work with Jenkins 2.0 yet. Anyway I'll install it here and try to fix the problems.

**Comment by jamroks** [comment]
Thanks for the feedback, no worries  , it's already looking pretty good to me so far. i'll just wait for the official availability .

**Comment by afonsof** [comment]
@jamroks I've just updated the theme to the version 1.2.2. No icon will be blank anymore. Unfortunately it increased the file size a little bit.

**Comment by jamroks** [comment]
@afonsof thanks for the update. unfortunately i think there is still a minor issue at least for Jenkins 2.0-Beta-1 . As you can see in the picture below:   

- The "manage jenkins" section on left side menu has an icon but it's from the default icon set of jenkins not a material design one. 
- Section "Configure Sytem" in the middle, has the the same old jenkins icon .

The icon should be looking more like the one used for "Global Tool Configuration" i guess .

Thanks

**Comment by jamroks** [comment]
<img width="1209" alt="screen shot 2016-03-25 at 08 47 33" src="https://cloud.githubusercontent.com/assets/357258/14040508/40705e40-f268-11e5-98a3-3e984c47ac89.png">

**Comment by afonsof** [comment]
@jamroks I know. The bug was not fixed. I did only one change in order to show not customized icons. As soon as possible I'll fix this one. Could you send me the html of this icon?

**Comment by wbagdon** [comment]
<img src="/static/5f4cb664/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md">
<img src="/static/5f4cb664/images/48x48/gear2.png" style="width: 48px; height: 48px; " class="icon-gear2 icon-xlg">

**Comment by wbagdon** [comment]
From settings page
`<img src="/static/5f4cb664/images/48x48/gear2.png" style="width: 48px; height: 48px; " class="icon-gear2 icon-xlg">`

From left toolbar
`<img src="/static/5f4cb664/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md">`

**Comment by mattrick16** [comment]
Jenkins 2.0 is now out of beta, so a fix should be considered.
