### ISSUE TITLE
Jekins 2.0 not working properly

### ISSUE THREAD

**Issue by dajos7** [jenkins-contrib-themes/jenkins-material-theme#64]
The theme is working on mainpage and some subpages of jenkins 2.0 as standalone plugin.. I guess would only take some minor adjustments for Jenknis 2 .. would be great to get this .. Theme is really awesome.

**Comment by afonsof** [comment]
Hi @dajos7. What are the problems you have identified?

**Comment by hgfischer** [comment]
Hi, I'm getting this not themed page: /me/my-views/view/All/

**Comment by hgfischer** [comment]
It looks like it's not working with views.

A detailed job view within a view doesn't work as well: 
Ex.: /view/VIEWNAME/job/JOBNAME/

**Comment by afonsof** [comment]
That's weird. In my case it's working properly
![image](https://cloud.githubusercontent.com/assets/805511/15796941/9757b8e8-29d6-11e6-85bf-4fd54ff10112.png)

Are you using any plugin? Is your version 1.2.3?

**Comment by hgfischer** [comment]
Hi @afonsof 

The *All* view also works fine for me. But it doesn't work with other custom views.

**Comment by hgfischer** [comment]
I was using a self-hosted version. Now, with the https://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-{{your-color-name}}.css URL, it's working fine.

**Comment by vlehm** [comment]
I had the same issue. However, after checking the parameter "Jenkins URL" and the URL to local content for correctness (starting slash, etc) it worked. If someone else runs into this, try playing around with those settings ;)
