### ISSUE TITLE
Customize the top bar color

### ISSUE THREAD

**Issue by vrenjith** [jenkins-contrib-themes/jenkins-material-theme#67]
This is help request rather than an issue. Do you have some quick steps how to go about modifying the colour of the top bar (which is currently this one I guess http://www.colorhexa.com/1d9888)

**Comment by wbagdon** [comment]
Change color-primary in the variables.less file
https://github.com/jenkins-contrib-themes/jenkins-material-theme/blob/master/less/variables.less

**Comment by afonsof** [comment]
@wbagdon thanks for answering the question. This is really a matter of changing the color-primary in variable.less file
