### ISSUE TITLE
Header too large

### ISSUE THREAD

**Issue by rdsubhas** [jenkins-contrib-themes/jenkins-material-theme#70]
The Top header is only rarely used. It has just the logo, search bar, username and logout link. Main functionality are all below it, and I find myself always having to scroll down to see useful stuff.

Can we please dedicate lesser area to the header bar, so that people have more visual space for more important stuff? Like bringing it down from 64px to 36px, and making the logo smaller?

**Comment by afonsof** [comment]
Thanks for filling out this issue! Unfortunately I've tried to decrease the header size but I looked too ugly. When I created this theme my intention was to make Jenkins good looking and improve the usability a little bit and in my opinion to shrink the toolbar would not bring any usability improvement neither make it more beautiful. Furthermore we are following the Material Design guideline and it says 64dp for desktop and tablets screens. For more information vistit: https://www.google.com/design/spec/layout/structure.html#structure-app-bar
